compressionLevel: 9

enableColors: false

enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

pnpEnableEsmLoader: true

packageExtensions:
  "@oxc-parser/binding-wasm32-wasi@0.120.0":
    dependencies:
      "@emnapi/core": "*"
      "@emnapi/runtime": "*"
  "oxc-parser@0.120.0":
    dependencies:
      "@emnapi/core": "*"
      "@emnapi/runtime": "*"
