/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './Layout'
import { Route as PagesShiftRouteImport } from './Pages/Shift'
import { Route as PagesProjectsLayoutRouteImport } from './Pages/ProjectsLayout'
import { Route as PagesLegalRouteImport } from './Pages/Legal'
import { Route as PagesHireRouteImport } from './Pages/Hire'
import { Route as PagesContactsRouteImport } from './Pages/Contacts'
import { Route as PagesBlogLayoutRouteImport } from './Pages/BlogLayout'
import { Route as PagesAboutRouteImport } from './Pages/About'
import { Route as PagesHomeRouteImport } from './Pages/Home'
import { Route as PagesProjectsSumicareRouteImport } from './Pages/Projects/Sumicare'
import { Route as PagesProjectsRCNARouteImport } from './Pages/Projects/RCNA'
import { Route as PagesBlog0_InitialRouteImport } from './Pages/Blog/0_Initial'
import { Route as PagesProjectsRouteImport } from './Pages/Projects'
import { Route as PagesBlogRouteImport } from './Pages/Blog'

const PagesShiftRoute = PagesShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesProjectsLayoutRoute = PagesProjectsLayoutRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLegalRoute = PagesLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHireRoute = PagesHireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactsRoute = PagesContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBlogLayoutRoute = PagesBlogLayoutRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHomeRoute = PagesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesProjectsSumicareRoute = PagesProjectsSumicareRouteImport.update({
  id: '/sumicare',
  path: '/sumicare',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesProjectsRCNARoute = PagesProjectsRCNARouteImport.update({
  id: '/rcna',
  path: '/rcna',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesBlog0_InitialRoute = PagesBlog0_InitialRouteImport.update({
  id: '/initial',
  path: '/initial',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesProjectsRoute = PagesProjectsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesBlogRoute = PagesBlogRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/blog': typeof PagesBlogLayoutRouteWithChildren
  '/contacts': typeof PagesContactsRoute
  '/hire': typeof PagesHireRoute
  '/legal': typeof PagesLegalRoute
  '/projects': typeof PagesProjectsLayoutRouteWithChildren
  '/shift': typeof PagesShiftRoute
  '/blog/': typeof PagesBlogRoute
  '/projects/': typeof PagesProjectsRoute
  '/blog/initial': typeof PagesBlog0_InitialRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/sumicare': typeof PagesProjectsSumicareRoute
}
export interface FileRoutesByTo {
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/contacts': typeof PagesContactsRoute
  '/hire': typeof PagesHireRoute
  '/legal': typeof PagesLegalRoute
  '/shift': typeof PagesShiftRoute
  '/blog': typeof PagesBlogRoute
  '/projects': typeof PagesProjectsRoute
  '/blog/initial': typeof PagesBlog0_InitialRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/sumicare': typeof PagesProjectsSumicareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/blog': typeof PagesBlogLayoutRouteWithChildren
  '/contacts': typeof PagesContactsRoute
  '/hire': typeof PagesHireRoute
  '/legal': typeof PagesLegalRoute
  '/projects': typeof PagesProjectsLayoutRouteWithChildren
  '/shift': typeof PagesShiftRoute
  '/blog/': typeof PagesBlogRoute
  '/projects/': typeof PagesProjectsRoute
  '/blog/initial': typeof PagesBlog0_InitialRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/sumicare': typeof PagesProjectsSumicareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/hire'
    | '/legal'
    | '/projects'
    | '/shift'
    | '/blog/'
    | '/projects/'
    | '/blog/initial'
    | '/projects/rcna'
    | '/projects/sumicare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/hire'
    | '/legal'
    | '/shift'
    | '/blog'
    | '/projects'
    | '/blog/initial'
    | '/projects/rcna'
    | '/projects/sumicare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/hire'
    | '/legal'
    | '/projects'
    | '/shift'
    | '/blog/'
    | '/projects/'
    | '/blog/initial'
    | '/projects/rcna'
    | '/projects/sumicare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesHomeRoute: typeof PagesHomeRoute
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBlogLayoutRoute: typeof PagesBlogLayoutRouteWithChildren
  PagesContactsRoute: typeof PagesContactsRoute
  PagesHireRoute: typeof PagesHireRoute
  PagesLegalRoute: typeof PagesLegalRoute
  PagesProjectsLayoutRoute: typeof PagesProjectsLayoutRouteWithChildren
  PagesShiftRoute: typeof PagesShiftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shift': {
      id: '/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof PagesShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PagesProjectsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PagesLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof PagesHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PagesContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PagesBlogLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sumicare': {
      id: '/projects/sumicare'
      path: '/sumicare'
      fullPath: '/projects/sumicare'
      preLoaderRoute: typeof PagesProjectsSumicareRouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/projects/rcna': {
      id: '/projects/rcna'
      path: '/rcna'
      fullPath: '/projects/rcna'
      preLoaderRoute: typeof PagesProjectsRCNARouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/blog/initial': {
      id: '/blog/initial'
      path: '/initial'
      fullPath: '/blog/initial'
      preLoaderRoute: typeof PagesBlog0_InitialRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof PagesProjectsRouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof PagesBlogRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
  }
}

interface PagesBlogLayoutRouteChildren {
  PagesBlogRoute: typeof PagesBlogRoute
  PagesBlog0_InitialRoute: typeof PagesBlog0_InitialRoute
}

const PagesBlogLayoutRouteChildren: PagesBlogLayoutRouteChildren = {
  PagesBlogRoute: PagesBlogRoute,
  PagesBlog0_InitialRoute: PagesBlog0_InitialRoute,
}

const PagesBlogLayoutRouteWithChildren = PagesBlogLayoutRoute._addFileChildren(
  PagesBlogLayoutRouteChildren,
)

interface PagesProjectsLayoutRouteChildren {
  PagesProjectsRoute: typeof PagesProjectsRoute
  PagesProjectsRCNARoute: typeof PagesProjectsRCNARoute
  PagesProjectsSumicareRoute: typeof PagesProjectsSumicareRoute
}

const PagesProjectsLayoutRouteChildren: PagesProjectsLayoutRouteChildren = {
  PagesProjectsRoute: PagesProjectsRoute,
  PagesProjectsRCNARoute: PagesProjectsRCNARoute,
  PagesProjectsSumicareRoute: PagesProjectsSumicareRoute,
}

const PagesProjectsLayoutRouteWithChildren =
  PagesProjectsLayoutRoute._addFileChildren(PagesProjectsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PagesHomeRoute: PagesHomeRoute,
  PagesAboutRoute: PagesAboutRoute,
  PagesBlogLayoutRoute: PagesBlogLayoutRouteWithChildren,
  PagesContactsRoute: PagesContactsRoute,
  PagesHireRoute: PagesHireRoute,
  PagesLegalRoute: PagesLegalRoute,
  PagesProjectsLayoutRoute: PagesProjectsLayoutRouteWithChildren,
  PagesShiftRoute: PagesShiftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
