/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './Layout'
import { Route as PagesShiftRouteImport } from './Pages/Shift'
import { Route as PagesProjectsLayoutRouteImport } from './Pages/ProjectsLayout'
import { Route as PagesLegalRouteImport } from './Pages/Legal'
import { Route as PagesHireLayoutRouteImport } from './Pages/HireLayout'
import { Route as PagesEventsLayoutRouteImport } from './Pages/EventsLayout'
import { Route as PagesContactsRouteImport } from './Pages/Contacts'
import { Route as PagesBlogLayoutRouteImport } from './Pages/BlogLayout'
import { Route as PagesAboutRouteImport } from './Pages/About'
import { Route as PagesHomeRouteImport } from './Pages/Home'
import { Route as PagesProjectsThenPlanRouteImport } from './Pages/Projects/ThenPlan'
import { Route as PagesProjectsRCNARouteImport } from './Pages/Projects/RCNA'
import { Route as PagesProjectsBitsnapRouteImport } from './Pages/Projects/Bitsnap'
import { Route as PagesHireDomainTelecomRouteImport } from './Pages/Hire/Domain/Telecom'
import { Route as PagesHireSimulationRouteImport } from './Pages/Hire/Simulation'
import { Route as PagesHireDomainSecurityRouteImport } from './Pages/Hire/Domain/Security'
import { Route as PagesHireActivitiesSalesRouteImport } from './Pages/Hire/Activities/Sales'
import { Route as PagesHireDomainResearchRouteImport } from './Pages/Hire/Domain/Research'
import { Route as PagesHireMachineLearningRouteImport } from './Pages/Hire/MachineLearning'
import { Route as PagesHireDomainLogisticsRouteImport } from './Pages/Hire/Domain/Logistics'
import { Route as PagesHireLanguagesRouteImport } from './Pages/Hire/Languages'
import { Route as PagesHireActivitiesKubernetesRouteImport } from './Pages/Hire/Activities/Kubernetes'
import { Route as PagesHireHighloadRouteImport } from './Pages/Hire/Highload'
import { Route as PagesHireActivitiesGCPRouteImport } from './Pages/Hire/Activities/GCP'
import { Route as PagesHireFrontendRouteImport } from './Pages/Hire/Frontend'
import { Route as PagesHireDomainFinTechRouteImport } from './Pages/Hire/Domain/FinTech'
import { Route as PagesHireEmbeddedRouteImport } from './Pages/Hire/Embedded'
import { Route as PagesHireDomainEdTechRouteImport } from './Pages/Hire/Domain/EdTech'
import { Route as PagesHireDeviceDriversRouteImport } from './Pages/Hire/DeviceDrivers'
import { Route as PagesHireActivitiesDiscoveryRouteImport } from './Pages/Hire/Activities/Discovery'
import { Route as PagesHireDevopsRouteImport } from './Pages/Hire/Devops'
import { Route as PagesHireDatabasesRouteImport } from './Pages/Hire/Databases'
import { Route as PagesHireCompilersRouteImport } from './Pages/Hire/Compilers'
import { Route as PagesHireActivitiesCareerRouteImport } from './Pages/Hire/Activities/Career'
import { Route as PagesHireCAERouteImport } from './Pages/Hire/CAE'
import { Route as PagesHireBackendRouteImport } from './Pages/Hire/Backend'
import { Route as PagesHireActivitiesAzureRouteImport } from './Pages/Hire/Activities/Azure'
import { Route as PagesHireActivitiesAWSRouteImport } from './Pages/Hire/Activities/AWS'
import { Route as PagesHireActivitiesArchitectureRouteImport } from './Pages/Hire/Activities/Architecture'
import { Route as PagesEventsThenPlanDemoRouteImport } from './Pages/Events/ThenPlanDemo'
import { Route as PagesEventsRCNADemoRouteImport } from './Pages/Events/RCNADemo'
import { Route as PagesEventsBitsnapDemoRouteImport } from './Pages/Events/BitsnapDemo'
import { Route as PagesBlog12_TelecomAppsRouteImport } from './Pages/Blog/12_TelecomApps'
import { Route as PagesBlog9_VisualControlAndSimulationsRouteImport } from './Pages/Blog/9_VisualControlAndSimulations'
import { Route as PagesBlog10_AgentsInControlSystemsRouteImport } from './Pages/Blog/10_AgentsInControlSystems'
import { Route as PagesBlog2_RCNARouteImport } from './Pages/Blog/2_RCNA'
import { Route as PagesBlog8_ModernControlTheoryRouteImport } from './Pages/Blog/8_ModernControlTheory'
import { Route as PagesBlog13_MLKernelsRouteImport } from './Pages/Blog/13_MLKernels'
import { Route as PagesBlog7_LogisticsRouteImport } from './Pages/Blog/7_Logistics'
import { Route as PagesBlog4_GCPRouteImport } from './Pages/Blog/4_GCP'
import { Route as PagesBlog14_FrontendAPIRouteImport } from './Pages/Blog/14_FrontendAPI'
import { Route as PagesBlog6_SolutionDiscoveryRouteImport } from './Pages/Blog/6_SolutionDiscovery'
import { Route as PagesBlog15_ModernControlInAdditiveRouteImport } from './Pages/Blog/15_ModernControlInAdditive'
import { Route as PagesBlog0_CareerFrameworkRouteImport } from './Pages/Blog/0_CareerFramework'
import { Route as PagesBlog3_AzureRouteImport } from './Pages/Blog/3_Azure'
import { Route as PagesBlog1_AWSRouteImport } from './Pages/Blog/1_AWS'
import { Route as PagesBlog16_PredictiveAutoscalingRouteImport } from './Pages/Blog/16_PredictiveAutoscaling'
import { Route as PagesBlog5_SolutionArchitectureRouteImport } from './Pages/Blog/5_SolutionArchitecture'
import { Route as PagesBlog11_AIInTelecomRouteImport } from './Pages/Blog/11_AIInTelecom'
import { Route as PagesProjectsRouteImport } from './Pages/Projects'
import { Route as PagesHireRouteImport } from './Pages/Hire'
import { Route as PagesEventsRouteImport } from './Pages/Events'
import { Route as PagesBlogRouteImport } from './Pages/Blog'

const PagesShiftRoute = PagesShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesProjectsLayoutRoute = PagesProjectsLayoutRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLegalRoute = PagesLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHireLayoutRoute = PagesHireLayoutRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesEventsLayoutRoute = PagesEventsLayoutRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactsRoute = PagesContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBlogLayoutRoute = PagesBlogLayoutRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHomeRoute = PagesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesProjectsThenPlanRoute = PagesProjectsThenPlanRouteImport.update({
  id: '/thenplan',
  path: '/thenplan',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesProjectsRCNARoute = PagesProjectsRCNARouteImport.update({
  id: '/rcna',
  path: '/rcna',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesProjectsBitsnapRoute = PagesProjectsBitsnapRouteImport.update({
  id: '/bitsnap',
  path: '/bitsnap',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesHireDomainTelecomRoute = PagesHireDomainTelecomRouteImport.update({
  id: '/telecom',
  path: '/telecom',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireSimulationRoute = PagesHireSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireDomainSecurityRoute = PagesHireDomainSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesSalesRoute =
  PagesHireActivitiesSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireDomainResearchRoute = PagesHireDomainResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireMachineLearningRoute =
  PagesHireMachineLearningRouteImport.update({
    id: '/ml',
    path: '/ml',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireDomainLogisticsRoute =
  PagesHireDomainLogisticsRouteImport.update({
    id: '/logistics',
    path: '/logistics',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireLanguagesRoute = PagesHireLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesKubernetesRoute =
  PagesHireActivitiesKubernetesRouteImport.update({
    id: '/kubernetes',
    path: '/kubernetes',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireHighloadRoute = PagesHireHighloadRouteImport.update({
  id: '/highload',
  path: '/highload',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesGCPRoute = PagesHireActivitiesGCPRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireFrontendRoute = PagesHireFrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireDomainFinTechRoute = PagesHireDomainFinTechRouteImport.update({
  id: '/fintech',
  path: '/fintech',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireEmbeddedRoute = PagesHireEmbeddedRouteImport.update({
  id: '/embedded',
  path: '/embedded',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireDomainEdTechRoute = PagesHireDomainEdTechRouteImport.update({
  id: '/edtech',
  path: '/edtech',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireDeviceDriversRoute = PagesHireDeviceDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesDiscoveryRoute =
  PagesHireActivitiesDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireDevopsRoute = PagesHireDevopsRouteImport.update({
  id: '/devops',
  path: '/devops',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireDatabasesRoute = PagesHireDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireCompilersRoute = PagesHireCompilersRouteImport.update({
  id: '/compilers',
  path: '/compilers',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesCareerRoute =
  PagesHireActivitiesCareerRouteImport.update({
    id: '/career',
    path: '/career',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireCAERoute = PagesHireCAERouteImport.update({
  id: '/cae',
  path: '/cae',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireBackendRoute = PagesHireBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesAzureRoute =
  PagesHireActivitiesAzureRouteImport.update({
    id: '/azure',
    path: '/azure',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesHireActivitiesAWSRoute = PagesHireActivitiesAWSRouteImport.update({
  id: '/aws',
  path: '/aws',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesHireActivitiesArchitectureRoute =
  PagesHireActivitiesArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => PagesHireLayoutRoute,
  } as any)
const PagesEventsThenPlanDemoRoute = PagesEventsThenPlanDemoRouteImport.update({
  id: '/thenplan',
  path: '/thenplan',
  getParentRoute: () => PagesEventsLayoutRoute,
} as any)
const PagesEventsRCNADemoRoute = PagesEventsRCNADemoRouteImport.update({
  id: '/rcna',
  path: '/rcna',
  getParentRoute: () => PagesEventsLayoutRoute,
} as any)
const PagesEventsBitsnapDemoRoute = PagesEventsBitsnapDemoRouteImport.update({
  id: '/bitsnap',
  path: '/bitsnap',
  getParentRoute: () => PagesEventsLayoutRoute,
} as any)
const PagesBlog12_TelecomAppsRoute = PagesBlog12_TelecomAppsRouteImport.update({
  id: '/telecom',
  path: '/telecom',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog9_VisualControlAndSimulationsRoute =
  PagesBlog9_VisualControlAndSimulationsRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog10_AgentsInControlSystemsRoute =
  PagesBlog10_AgentsInControlSystemsRouteImport.update({
    id: '/self-organizing-control',
    path: '/self-organizing-control',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog2_RCNARoute = PagesBlog2_RCNARouteImport.update({
  id: '/rcna',
  path: '/rcna',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog8_ModernControlTheoryRoute =
  PagesBlog8_ModernControlTheoryRouteImport.update({
    id: '/modern-control-theory',
    path: '/modern-control-theory',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog13_MLKernelsRoute = PagesBlog13_MLKernelsRouteImport.update({
  id: '/ml-kernels',
  path: '/ml-kernels',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog7_LogisticsRoute = PagesBlog7_LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog4_GCPRoute = PagesBlog4_GCPRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog14_FrontendAPIRoute = PagesBlog14_FrontendAPIRouteImport.update({
  id: '/frontend-apis',
  path: '/frontend-apis',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog6_SolutionDiscoveryRoute =
  PagesBlog6_SolutionDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog15_ModernControlInAdditiveRoute =
  PagesBlog15_ModernControlInAdditiveRouteImport.update({
    id: '/control-manufacturing',
    path: '/control-manufacturing',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog0_CareerFrameworkRoute =
  PagesBlog0_CareerFrameworkRouteImport.update({
    id: '/career',
    path: '/career',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog3_AzureRoute = PagesBlog3_AzureRouteImport.update({
  id: '/azure',
  path: '/azure',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog1_AWSRoute = PagesBlog1_AWSRouteImport.update({
  id: '/aws',
  path: '/aws',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesBlog16_PredictiveAutoscalingRoute =
  PagesBlog16_PredictiveAutoscalingRouteImport.update({
    id: '/autoscaling',
    path: '/autoscaling',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog5_SolutionArchitectureRoute =
  PagesBlog5_SolutionArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => PagesBlogLayoutRoute,
  } as any)
const PagesBlog11_AIInTelecomRoute = PagesBlog11_AIInTelecomRouteImport.update({
  id: '/ai-in-telecom',
  path: '/ai-in-telecom',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)
const PagesProjectsRoute = PagesProjectsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesProjectsLayoutRoute,
} as any)
const PagesHireRoute = PagesHireRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesHireLayoutRoute,
} as any)
const PagesEventsRoute = PagesEventsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesEventsLayoutRoute,
} as any)
const PagesBlogRoute = PagesBlogRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesBlogLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/blog': typeof PagesBlogLayoutRouteWithChildren
  '/contacts': typeof PagesContactsRoute
  '/events': typeof PagesEventsLayoutRouteWithChildren
  '/hire': typeof PagesHireLayoutRouteWithChildren
  '/legal': typeof PagesLegalRoute
  '/projects': typeof PagesProjectsLayoutRouteWithChildren
  '/shift': typeof PagesShiftRoute
  '/blog/': typeof PagesBlogRoute
  '/events/': typeof PagesEventsRoute
  '/hire/': typeof PagesHireRoute
  '/projects/': typeof PagesProjectsRoute
  '/blog/ai-in-telecom': typeof PagesBlog11_AIInTelecomRoute
  '/blog/architecture': typeof PagesBlog5_SolutionArchitectureRoute
  '/blog/autoscaling': typeof PagesBlog16_PredictiveAutoscalingRoute
  '/blog/aws': typeof PagesBlog1_AWSRoute
  '/blog/azure': typeof PagesBlog3_AzureRoute
  '/blog/career': typeof PagesBlog0_CareerFrameworkRoute
  '/blog/control-manufacturing': typeof PagesBlog15_ModernControlInAdditiveRoute
  '/blog/discovery': typeof PagesBlog6_SolutionDiscoveryRoute
  '/blog/frontend-apis': typeof PagesBlog14_FrontendAPIRoute
  '/blog/gcp': typeof PagesBlog4_GCPRoute
  '/blog/logistics': typeof PagesBlog7_LogisticsRoute
  '/blog/ml-kernels': typeof PagesBlog13_MLKernelsRoute
  '/blog/modern-control-theory': typeof PagesBlog8_ModernControlTheoryRoute
  '/blog/rcna': typeof PagesBlog2_RCNARoute
  '/blog/self-organizing-control': typeof PagesBlog10_AgentsInControlSystemsRoute
  '/blog/simulation': typeof PagesBlog9_VisualControlAndSimulationsRoute
  '/blog/telecom': typeof PagesBlog12_TelecomAppsRoute
  '/events/bitsnap': typeof PagesEventsBitsnapDemoRoute
  '/events/rcna': typeof PagesEventsRCNADemoRoute
  '/events/thenplan': typeof PagesEventsThenPlanDemoRoute
  '/hire/architecture': typeof PagesHireActivitiesArchitectureRoute
  '/hire/aws': typeof PagesHireActivitiesAWSRoute
  '/hire/azure': typeof PagesHireActivitiesAzureRoute
  '/hire/backend': typeof PagesHireBackendRoute
  '/hire/cae': typeof PagesHireCAERoute
  '/hire/career': typeof PagesHireActivitiesCareerRoute
  '/hire/compilers': typeof PagesHireCompilersRoute
  '/hire/databases': typeof PagesHireDatabasesRoute
  '/hire/devops': typeof PagesHireDevopsRoute
  '/hire/discovery': typeof PagesHireActivitiesDiscoveryRoute
  '/hire/drivers': typeof PagesHireDeviceDriversRoute
  '/hire/edtech': typeof PagesHireDomainEdTechRoute
  '/hire/embedded': typeof PagesHireEmbeddedRoute
  '/hire/fintech': typeof PagesHireDomainFinTechRoute
  '/hire/frontend': typeof PagesHireFrontendRoute
  '/hire/gcp': typeof PagesHireActivitiesGCPRoute
  '/hire/highload': typeof PagesHireHighloadRoute
  '/hire/kubernetes': typeof PagesHireActivitiesKubernetesRoute
  '/hire/languages': typeof PagesHireLanguagesRoute
  '/hire/logistics': typeof PagesHireDomainLogisticsRoute
  '/hire/ml': typeof PagesHireMachineLearningRoute
  '/hire/research': typeof PagesHireDomainResearchRoute
  '/hire/sales': typeof PagesHireActivitiesSalesRoute
  '/hire/security': typeof PagesHireDomainSecurityRoute
  '/hire/simulation': typeof PagesHireSimulationRoute
  '/hire/telecom': typeof PagesHireDomainTelecomRoute
  '/projects/bitsnap': typeof PagesProjectsBitsnapRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/thenplan': typeof PagesProjectsThenPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/contacts': typeof PagesContactsRoute
  '/legal': typeof PagesLegalRoute
  '/shift': typeof PagesShiftRoute
  '/blog': typeof PagesBlogRoute
  '/events': typeof PagesEventsRoute
  '/hire': typeof PagesHireRoute
  '/projects': typeof PagesProjectsRoute
  '/blog/ai-in-telecom': typeof PagesBlog11_AIInTelecomRoute
  '/blog/architecture': typeof PagesBlog5_SolutionArchitectureRoute
  '/blog/autoscaling': typeof PagesBlog16_PredictiveAutoscalingRoute
  '/blog/aws': typeof PagesBlog1_AWSRoute
  '/blog/azure': typeof PagesBlog3_AzureRoute
  '/blog/career': typeof PagesBlog0_CareerFrameworkRoute
  '/blog/control-manufacturing': typeof PagesBlog15_ModernControlInAdditiveRoute
  '/blog/discovery': typeof PagesBlog6_SolutionDiscoveryRoute
  '/blog/frontend-apis': typeof PagesBlog14_FrontendAPIRoute
  '/blog/gcp': typeof PagesBlog4_GCPRoute
  '/blog/logistics': typeof PagesBlog7_LogisticsRoute
  '/blog/ml-kernels': typeof PagesBlog13_MLKernelsRoute
  '/blog/modern-control-theory': typeof PagesBlog8_ModernControlTheoryRoute
  '/blog/rcna': typeof PagesBlog2_RCNARoute
  '/blog/self-organizing-control': typeof PagesBlog10_AgentsInControlSystemsRoute
  '/blog/simulation': typeof PagesBlog9_VisualControlAndSimulationsRoute
  '/blog/telecom': typeof PagesBlog12_TelecomAppsRoute
  '/events/bitsnap': typeof PagesEventsBitsnapDemoRoute
  '/events/rcna': typeof PagesEventsRCNADemoRoute
  '/events/thenplan': typeof PagesEventsThenPlanDemoRoute
  '/hire/architecture': typeof PagesHireActivitiesArchitectureRoute
  '/hire/aws': typeof PagesHireActivitiesAWSRoute
  '/hire/azure': typeof PagesHireActivitiesAzureRoute
  '/hire/backend': typeof PagesHireBackendRoute
  '/hire/cae': typeof PagesHireCAERoute
  '/hire/career': typeof PagesHireActivitiesCareerRoute
  '/hire/compilers': typeof PagesHireCompilersRoute
  '/hire/databases': typeof PagesHireDatabasesRoute
  '/hire/devops': typeof PagesHireDevopsRoute
  '/hire/discovery': typeof PagesHireActivitiesDiscoveryRoute
  '/hire/drivers': typeof PagesHireDeviceDriversRoute
  '/hire/edtech': typeof PagesHireDomainEdTechRoute
  '/hire/embedded': typeof PagesHireEmbeddedRoute
  '/hire/fintech': typeof PagesHireDomainFinTechRoute
  '/hire/frontend': typeof PagesHireFrontendRoute
  '/hire/gcp': typeof PagesHireActivitiesGCPRoute
  '/hire/highload': typeof PagesHireHighloadRoute
  '/hire/kubernetes': typeof PagesHireActivitiesKubernetesRoute
  '/hire/languages': typeof PagesHireLanguagesRoute
  '/hire/logistics': typeof PagesHireDomainLogisticsRoute
  '/hire/ml': typeof PagesHireMachineLearningRoute
  '/hire/research': typeof PagesHireDomainResearchRoute
  '/hire/sales': typeof PagesHireActivitiesSalesRoute
  '/hire/security': typeof PagesHireDomainSecurityRoute
  '/hire/simulation': typeof PagesHireSimulationRoute
  '/hire/telecom': typeof PagesHireDomainTelecomRoute
  '/projects/bitsnap': typeof PagesProjectsBitsnapRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/thenplan': typeof PagesProjectsThenPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PagesHomeRoute
  '/about': typeof PagesAboutRoute
  '/blog': typeof PagesBlogLayoutRouteWithChildren
  '/contacts': typeof PagesContactsRoute
  '/events': typeof PagesEventsLayoutRouteWithChildren
  '/hire': typeof PagesHireLayoutRouteWithChildren
  '/legal': typeof PagesLegalRoute
  '/projects': typeof PagesProjectsLayoutRouteWithChildren
  '/shift': typeof PagesShiftRoute
  '/blog/': typeof PagesBlogRoute
  '/events/': typeof PagesEventsRoute
  '/hire/': typeof PagesHireRoute
  '/projects/': typeof PagesProjectsRoute
  '/blog/ai-in-telecom': typeof PagesBlog11_AIInTelecomRoute
  '/blog/architecture': typeof PagesBlog5_SolutionArchitectureRoute
  '/blog/autoscaling': typeof PagesBlog16_PredictiveAutoscalingRoute
  '/blog/aws': typeof PagesBlog1_AWSRoute
  '/blog/azure': typeof PagesBlog3_AzureRoute
  '/blog/career': typeof PagesBlog0_CareerFrameworkRoute
  '/blog/control-manufacturing': typeof PagesBlog15_ModernControlInAdditiveRoute
  '/blog/discovery': typeof PagesBlog6_SolutionDiscoveryRoute
  '/blog/frontend-apis': typeof PagesBlog14_FrontendAPIRoute
  '/blog/gcp': typeof PagesBlog4_GCPRoute
  '/blog/logistics': typeof PagesBlog7_LogisticsRoute
  '/blog/ml-kernels': typeof PagesBlog13_MLKernelsRoute
  '/blog/modern-control-theory': typeof PagesBlog8_ModernControlTheoryRoute
  '/blog/rcna': typeof PagesBlog2_RCNARoute
  '/blog/self-organizing-control': typeof PagesBlog10_AgentsInControlSystemsRoute
  '/blog/simulation': typeof PagesBlog9_VisualControlAndSimulationsRoute
  '/blog/telecom': typeof PagesBlog12_TelecomAppsRoute
  '/events/bitsnap': typeof PagesEventsBitsnapDemoRoute
  '/events/rcna': typeof PagesEventsRCNADemoRoute
  '/events/thenplan': typeof PagesEventsThenPlanDemoRoute
  '/hire/architecture': typeof PagesHireActivitiesArchitectureRoute
  '/hire/aws': typeof PagesHireActivitiesAWSRoute
  '/hire/azure': typeof PagesHireActivitiesAzureRoute
  '/hire/backend': typeof PagesHireBackendRoute
  '/hire/cae': typeof PagesHireCAERoute
  '/hire/career': typeof PagesHireActivitiesCareerRoute
  '/hire/compilers': typeof PagesHireCompilersRoute
  '/hire/databases': typeof PagesHireDatabasesRoute
  '/hire/devops': typeof PagesHireDevopsRoute
  '/hire/discovery': typeof PagesHireActivitiesDiscoveryRoute
  '/hire/drivers': typeof PagesHireDeviceDriversRoute
  '/hire/edtech': typeof PagesHireDomainEdTechRoute
  '/hire/embedded': typeof PagesHireEmbeddedRoute
  '/hire/fintech': typeof PagesHireDomainFinTechRoute
  '/hire/frontend': typeof PagesHireFrontendRoute
  '/hire/gcp': typeof PagesHireActivitiesGCPRoute
  '/hire/highload': typeof PagesHireHighloadRoute
  '/hire/kubernetes': typeof PagesHireActivitiesKubernetesRoute
  '/hire/languages': typeof PagesHireLanguagesRoute
  '/hire/logistics': typeof PagesHireDomainLogisticsRoute
  '/hire/ml': typeof PagesHireMachineLearningRoute
  '/hire/research': typeof PagesHireDomainResearchRoute
  '/hire/sales': typeof PagesHireActivitiesSalesRoute
  '/hire/security': typeof PagesHireDomainSecurityRoute
  '/hire/simulation': typeof PagesHireSimulationRoute
  '/hire/telecom': typeof PagesHireDomainTelecomRoute
  '/projects/bitsnap': typeof PagesProjectsBitsnapRoute
  '/projects/rcna': typeof PagesProjectsRCNARoute
  '/projects/thenplan': typeof PagesProjectsThenPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/events'
    | '/hire'
    | '/legal'
    | '/projects'
    | '/shift'
    | '/blog/'
    | '/events/'
    | '/hire/'
    | '/projects/'
    | '/blog/ai-in-telecom'
    | '/blog/architecture'
    | '/blog/autoscaling'
    | '/blog/aws'
    | '/blog/azure'
    | '/blog/career'
    | '/blog/control-manufacturing'
    | '/blog/discovery'
    | '/blog/frontend-apis'
    | '/blog/gcp'
    | '/blog/logistics'
    | '/blog/ml-kernels'
    | '/blog/modern-control-theory'
    | '/blog/rcna'
    | '/blog/self-organizing-control'
    | '/blog/simulation'
    | '/blog/telecom'
    | '/events/bitsnap'
    | '/events/rcna'
    | '/events/thenplan'
    | '/hire/architecture'
    | '/hire/aws'
    | '/hire/azure'
    | '/hire/backend'
    | '/hire/cae'
    | '/hire/career'
    | '/hire/compilers'
    | '/hire/databases'
    | '/hire/devops'
    | '/hire/discovery'
    | '/hire/drivers'
    | '/hire/edtech'
    | '/hire/embedded'
    | '/hire/fintech'
    | '/hire/frontend'
    | '/hire/gcp'
    | '/hire/highload'
    | '/hire/kubernetes'
    | '/hire/languages'
    | '/hire/logistics'
    | '/hire/ml'
    | '/hire/research'
    | '/hire/sales'
    | '/hire/security'
    | '/hire/simulation'
    | '/hire/telecom'
    | '/projects/bitsnap'
    | '/projects/rcna'
    | '/projects/thenplan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/legal'
    | '/shift'
    | '/blog'
    | '/events'
    | '/hire'
    | '/projects'
    | '/blog/ai-in-telecom'
    | '/blog/architecture'
    | '/blog/autoscaling'
    | '/blog/aws'
    | '/blog/azure'
    | '/blog/career'
    | '/blog/control-manufacturing'
    | '/blog/discovery'
    | '/blog/frontend-apis'
    | '/blog/gcp'
    | '/blog/logistics'
    | '/blog/ml-kernels'
    | '/blog/modern-control-theory'
    | '/blog/rcna'
    | '/blog/self-organizing-control'
    | '/blog/simulation'
    | '/blog/telecom'
    | '/events/bitsnap'
    | '/events/rcna'
    | '/events/thenplan'
    | '/hire/architecture'
    | '/hire/aws'
    | '/hire/azure'
    | '/hire/backend'
    | '/hire/cae'
    | '/hire/career'
    | '/hire/compilers'
    | '/hire/databases'
    | '/hire/devops'
    | '/hire/discovery'
    | '/hire/drivers'
    | '/hire/edtech'
    | '/hire/embedded'
    | '/hire/fintech'
    | '/hire/frontend'
    | '/hire/gcp'
    | '/hire/highload'
    | '/hire/kubernetes'
    | '/hire/languages'
    | '/hire/logistics'
    | '/hire/ml'
    | '/hire/research'
    | '/hire/sales'
    | '/hire/security'
    | '/hire/simulation'
    | '/hire/telecom'
    | '/projects/bitsnap'
    | '/projects/rcna'
    | '/projects/thenplan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/events'
    | '/hire'
    | '/legal'
    | '/projects'
    | '/shift'
    | '/blog/'
    | '/events/'
    | '/hire/'
    | '/projects/'
    | '/blog/ai-in-telecom'
    | '/blog/architecture'
    | '/blog/autoscaling'
    | '/blog/aws'
    | '/blog/azure'
    | '/blog/career'
    | '/blog/control-manufacturing'
    | '/blog/discovery'
    | '/blog/frontend-apis'
    | '/blog/gcp'
    | '/blog/logistics'
    | '/blog/ml-kernels'
    | '/blog/modern-control-theory'
    | '/blog/rcna'
    | '/blog/self-organizing-control'
    | '/blog/simulation'
    | '/blog/telecom'
    | '/events/bitsnap'
    | '/events/rcna'
    | '/events/thenplan'
    | '/hire/architecture'
    | '/hire/aws'
    | '/hire/azure'
    | '/hire/backend'
    | '/hire/cae'
    | '/hire/career'
    | '/hire/compilers'
    | '/hire/databases'
    | '/hire/devops'
    | '/hire/discovery'
    | '/hire/drivers'
    | '/hire/edtech'
    | '/hire/embedded'
    | '/hire/fintech'
    | '/hire/frontend'
    | '/hire/gcp'
    | '/hire/highload'
    | '/hire/kubernetes'
    | '/hire/languages'
    | '/hire/logistics'
    | '/hire/ml'
    | '/hire/research'
    | '/hire/sales'
    | '/hire/security'
    | '/hire/simulation'
    | '/hire/telecom'
    | '/projects/bitsnap'
    | '/projects/rcna'
    | '/projects/thenplan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesHomeRoute: typeof PagesHomeRoute
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBlogLayoutRoute: typeof PagesBlogLayoutRouteWithChildren
  PagesContactsRoute: typeof PagesContactsRoute
  PagesEventsLayoutRoute: typeof PagesEventsLayoutRouteWithChildren
  PagesHireLayoutRoute: typeof PagesHireLayoutRouteWithChildren
  PagesLegalRoute: typeof PagesLegalRoute
  PagesProjectsLayoutRoute: typeof PagesProjectsLayoutRouteWithChildren
  PagesShiftRoute: typeof PagesShiftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shift': {
      id: '/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof PagesShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PagesProjectsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PagesLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof PagesHireLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PagesEventsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PagesContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PagesBlogLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/thenplan': {
      id: '/projects/thenplan'
      path: '/thenplan'
      fullPath: '/projects/thenplan'
      preLoaderRoute: typeof PagesProjectsThenPlanRouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/projects/rcna': {
      id: '/projects/rcna'
      path: '/rcna'
      fullPath: '/projects/rcna'
      preLoaderRoute: typeof PagesProjectsRCNARouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/projects/bitsnap': {
      id: '/projects/bitsnap'
      path: '/bitsnap'
      fullPath: '/projects/bitsnap'
      preLoaderRoute: typeof PagesProjectsBitsnapRouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/hire/telecom': {
      id: '/hire/telecom'
      path: '/telecom'
      fullPath: '/hire/telecom'
      preLoaderRoute: typeof PagesHireDomainTelecomRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/simulation': {
      id: '/hire/simulation'
      path: '/simulation'
      fullPath: '/hire/simulation'
      preLoaderRoute: typeof PagesHireSimulationRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/security': {
      id: '/hire/security'
      path: '/security'
      fullPath: '/hire/security'
      preLoaderRoute: typeof PagesHireDomainSecurityRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/sales': {
      id: '/hire/sales'
      path: '/sales'
      fullPath: '/hire/sales'
      preLoaderRoute: typeof PagesHireActivitiesSalesRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/research': {
      id: '/hire/research'
      path: '/research'
      fullPath: '/hire/research'
      preLoaderRoute: typeof PagesHireDomainResearchRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/ml': {
      id: '/hire/ml'
      path: '/ml'
      fullPath: '/hire/ml'
      preLoaderRoute: typeof PagesHireMachineLearningRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/logistics': {
      id: '/hire/logistics'
      path: '/logistics'
      fullPath: '/hire/logistics'
      preLoaderRoute: typeof PagesHireDomainLogisticsRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/languages': {
      id: '/hire/languages'
      path: '/languages'
      fullPath: '/hire/languages'
      preLoaderRoute: typeof PagesHireLanguagesRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/kubernetes': {
      id: '/hire/kubernetes'
      path: '/kubernetes'
      fullPath: '/hire/kubernetes'
      preLoaderRoute: typeof PagesHireActivitiesKubernetesRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/highload': {
      id: '/hire/highload'
      path: '/highload'
      fullPath: '/hire/highload'
      preLoaderRoute: typeof PagesHireHighloadRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/gcp': {
      id: '/hire/gcp'
      path: '/gcp'
      fullPath: '/hire/gcp'
      preLoaderRoute: typeof PagesHireActivitiesGCPRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/frontend': {
      id: '/hire/frontend'
      path: '/frontend'
      fullPath: '/hire/frontend'
      preLoaderRoute: typeof PagesHireFrontendRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/fintech': {
      id: '/hire/fintech'
      path: '/fintech'
      fullPath: '/hire/fintech'
      preLoaderRoute: typeof PagesHireDomainFinTechRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/embedded': {
      id: '/hire/embedded'
      path: '/embedded'
      fullPath: '/hire/embedded'
      preLoaderRoute: typeof PagesHireEmbeddedRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/edtech': {
      id: '/hire/edtech'
      path: '/edtech'
      fullPath: '/hire/edtech'
      preLoaderRoute: typeof PagesHireDomainEdTechRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/drivers': {
      id: '/hire/drivers'
      path: '/drivers'
      fullPath: '/hire/drivers'
      preLoaderRoute: typeof PagesHireDeviceDriversRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/discovery': {
      id: '/hire/discovery'
      path: '/discovery'
      fullPath: '/hire/discovery'
      preLoaderRoute: typeof PagesHireActivitiesDiscoveryRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/devops': {
      id: '/hire/devops'
      path: '/devops'
      fullPath: '/hire/devops'
      preLoaderRoute: typeof PagesHireDevopsRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/databases': {
      id: '/hire/databases'
      path: '/databases'
      fullPath: '/hire/databases'
      preLoaderRoute: typeof PagesHireDatabasesRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/compilers': {
      id: '/hire/compilers'
      path: '/compilers'
      fullPath: '/hire/compilers'
      preLoaderRoute: typeof PagesHireCompilersRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/career': {
      id: '/hire/career'
      path: '/career'
      fullPath: '/hire/career'
      preLoaderRoute: typeof PagesHireActivitiesCareerRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/cae': {
      id: '/hire/cae'
      path: '/cae'
      fullPath: '/hire/cae'
      preLoaderRoute: typeof PagesHireCAERouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/backend': {
      id: '/hire/backend'
      path: '/backend'
      fullPath: '/hire/backend'
      preLoaderRoute: typeof PagesHireBackendRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/azure': {
      id: '/hire/azure'
      path: '/azure'
      fullPath: '/hire/azure'
      preLoaderRoute: typeof PagesHireActivitiesAzureRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/aws': {
      id: '/hire/aws'
      path: '/aws'
      fullPath: '/hire/aws'
      preLoaderRoute: typeof PagesHireActivitiesAWSRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/hire/architecture': {
      id: '/hire/architecture'
      path: '/architecture'
      fullPath: '/hire/architecture'
      preLoaderRoute: typeof PagesHireActivitiesArchitectureRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/events/thenplan': {
      id: '/events/thenplan'
      path: '/thenplan'
      fullPath: '/events/thenplan'
      preLoaderRoute: typeof PagesEventsThenPlanDemoRouteImport
      parentRoute: typeof PagesEventsLayoutRoute
    }
    '/events/rcna': {
      id: '/events/rcna'
      path: '/rcna'
      fullPath: '/events/rcna'
      preLoaderRoute: typeof PagesEventsRCNADemoRouteImport
      parentRoute: typeof PagesEventsLayoutRoute
    }
    '/events/bitsnap': {
      id: '/events/bitsnap'
      path: '/bitsnap'
      fullPath: '/events/bitsnap'
      preLoaderRoute: typeof PagesEventsBitsnapDemoRouteImport
      parentRoute: typeof PagesEventsLayoutRoute
    }
    '/blog/telecom': {
      id: '/blog/telecom'
      path: '/telecom'
      fullPath: '/blog/telecom'
      preLoaderRoute: typeof PagesBlog12_TelecomAppsRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/simulation': {
      id: '/blog/simulation'
      path: '/simulation'
      fullPath: '/blog/simulation'
      preLoaderRoute: typeof PagesBlog9_VisualControlAndSimulationsRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/self-organizing-control': {
      id: '/blog/self-organizing-control'
      path: '/self-organizing-control'
      fullPath: '/blog/self-organizing-control'
      preLoaderRoute: typeof PagesBlog10_AgentsInControlSystemsRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/rcna': {
      id: '/blog/rcna'
      path: '/rcna'
      fullPath: '/blog/rcna'
      preLoaderRoute: typeof PagesBlog2_RCNARouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/modern-control-theory': {
      id: '/blog/modern-control-theory'
      path: '/modern-control-theory'
      fullPath: '/blog/modern-control-theory'
      preLoaderRoute: typeof PagesBlog8_ModernControlTheoryRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/ml-kernels': {
      id: '/blog/ml-kernels'
      path: '/ml-kernels'
      fullPath: '/blog/ml-kernels'
      preLoaderRoute: typeof PagesBlog13_MLKernelsRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/logistics': {
      id: '/blog/logistics'
      path: '/logistics'
      fullPath: '/blog/logistics'
      preLoaderRoute: typeof PagesBlog7_LogisticsRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/gcp': {
      id: '/blog/gcp'
      path: '/gcp'
      fullPath: '/blog/gcp'
      preLoaderRoute: typeof PagesBlog4_GCPRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/frontend-apis': {
      id: '/blog/frontend-apis'
      path: '/frontend-apis'
      fullPath: '/blog/frontend-apis'
      preLoaderRoute: typeof PagesBlog14_FrontendAPIRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/discovery': {
      id: '/blog/discovery'
      path: '/discovery'
      fullPath: '/blog/discovery'
      preLoaderRoute: typeof PagesBlog6_SolutionDiscoveryRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/control-manufacturing': {
      id: '/blog/control-manufacturing'
      path: '/control-manufacturing'
      fullPath: '/blog/control-manufacturing'
      preLoaderRoute: typeof PagesBlog15_ModernControlInAdditiveRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/career': {
      id: '/blog/career'
      path: '/career'
      fullPath: '/blog/career'
      preLoaderRoute: typeof PagesBlog0_CareerFrameworkRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/azure': {
      id: '/blog/azure'
      path: '/azure'
      fullPath: '/blog/azure'
      preLoaderRoute: typeof PagesBlog3_AzureRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/aws': {
      id: '/blog/aws'
      path: '/aws'
      fullPath: '/blog/aws'
      preLoaderRoute: typeof PagesBlog1_AWSRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/autoscaling': {
      id: '/blog/autoscaling'
      path: '/autoscaling'
      fullPath: '/blog/autoscaling'
      preLoaderRoute: typeof PagesBlog16_PredictiveAutoscalingRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/architecture': {
      id: '/blog/architecture'
      path: '/architecture'
      fullPath: '/blog/architecture'
      preLoaderRoute: typeof PagesBlog5_SolutionArchitectureRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/blog/ai-in-telecom': {
      id: '/blog/ai-in-telecom'
      path: '/ai-in-telecom'
      fullPath: '/blog/ai-in-telecom'
      preLoaderRoute: typeof PagesBlog11_AIInTelecomRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof PagesProjectsRouteImport
      parentRoute: typeof PagesProjectsLayoutRoute
    }
    '/hire/': {
      id: '/hire/'
      path: '/'
      fullPath: '/hire/'
      preLoaderRoute: typeof PagesHireRouteImport
      parentRoute: typeof PagesHireLayoutRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof PagesEventsRouteImport
      parentRoute: typeof PagesEventsLayoutRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof PagesBlogRouteImport
      parentRoute: typeof PagesBlogLayoutRoute
    }
  }
}

interface PagesBlogLayoutRouteChildren {
  PagesBlogRoute: typeof PagesBlogRoute
  PagesBlog11_AIInTelecomRoute: typeof PagesBlog11_AIInTelecomRoute
  PagesBlog5_SolutionArchitectureRoute: typeof PagesBlog5_SolutionArchitectureRoute
  PagesBlog16_PredictiveAutoscalingRoute: typeof PagesBlog16_PredictiveAutoscalingRoute
  PagesBlog1_AWSRoute: typeof PagesBlog1_AWSRoute
  PagesBlog3_AzureRoute: typeof PagesBlog3_AzureRoute
  PagesBlog0_CareerFrameworkRoute: typeof PagesBlog0_CareerFrameworkRoute
  PagesBlog15_ModernControlInAdditiveRoute: typeof PagesBlog15_ModernControlInAdditiveRoute
  PagesBlog6_SolutionDiscoveryRoute: typeof PagesBlog6_SolutionDiscoveryRoute
  PagesBlog14_FrontendAPIRoute: typeof PagesBlog14_FrontendAPIRoute
  PagesBlog4_GCPRoute: typeof PagesBlog4_GCPRoute
  PagesBlog7_LogisticsRoute: typeof PagesBlog7_LogisticsRoute
  PagesBlog13_MLKernelsRoute: typeof PagesBlog13_MLKernelsRoute
  PagesBlog8_ModernControlTheoryRoute: typeof PagesBlog8_ModernControlTheoryRoute
  PagesBlog2_RCNARoute: typeof PagesBlog2_RCNARoute
  PagesBlog10_AgentsInControlSystemsRoute: typeof PagesBlog10_AgentsInControlSystemsRoute
  PagesBlog9_VisualControlAndSimulationsRoute: typeof PagesBlog9_VisualControlAndSimulationsRoute
  PagesBlog12_TelecomAppsRoute: typeof PagesBlog12_TelecomAppsRoute
}

const PagesBlogLayoutRouteChildren: PagesBlogLayoutRouteChildren = {
  PagesBlogRoute: PagesBlogRoute,
  PagesBlog11_AIInTelecomRoute: PagesBlog11_AIInTelecomRoute,
  PagesBlog5_SolutionArchitectureRoute: PagesBlog5_SolutionArchitectureRoute,
  PagesBlog16_PredictiveAutoscalingRoute:
    PagesBlog16_PredictiveAutoscalingRoute,
  PagesBlog1_AWSRoute: PagesBlog1_AWSRoute,
  PagesBlog3_AzureRoute: PagesBlog3_AzureRoute,
  PagesBlog0_CareerFrameworkRoute: PagesBlog0_CareerFrameworkRoute,
  PagesBlog15_ModernControlInAdditiveRoute:
    PagesBlog15_ModernControlInAdditiveRoute,
  PagesBlog6_SolutionDiscoveryRoute: PagesBlog6_SolutionDiscoveryRoute,
  PagesBlog14_FrontendAPIRoute: PagesBlog14_FrontendAPIRoute,
  PagesBlog4_GCPRoute: PagesBlog4_GCPRoute,
  PagesBlog7_LogisticsRoute: PagesBlog7_LogisticsRoute,
  PagesBlog13_MLKernelsRoute: PagesBlog13_MLKernelsRoute,
  PagesBlog8_ModernControlTheoryRoute: PagesBlog8_ModernControlTheoryRoute,
  PagesBlog2_RCNARoute: PagesBlog2_RCNARoute,
  PagesBlog10_AgentsInControlSystemsRoute:
    PagesBlog10_AgentsInControlSystemsRoute,
  PagesBlog9_VisualControlAndSimulationsRoute:
    PagesBlog9_VisualControlAndSimulationsRoute,
  PagesBlog12_TelecomAppsRoute: PagesBlog12_TelecomAppsRoute,
}

const PagesBlogLayoutRouteWithChildren = PagesBlogLayoutRoute._addFileChildren(
  PagesBlogLayoutRouteChildren,
)

interface PagesEventsLayoutRouteChildren {
  PagesEventsRoute: typeof PagesEventsRoute
  PagesEventsBitsnapDemoRoute: typeof PagesEventsBitsnapDemoRoute
  PagesEventsRCNADemoRoute: typeof PagesEventsRCNADemoRoute
  PagesEventsThenPlanDemoRoute: typeof PagesEventsThenPlanDemoRoute
}

const PagesEventsLayoutRouteChildren: PagesEventsLayoutRouteChildren = {
  PagesEventsRoute: PagesEventsRoute,
  PagesEventsBitsnapDemoRoute: PagesEventsBitsnapDemoRoute,
  PagesEventsRCNADemoRoute: PagesEventsRCNADemoRoute,
  PagesEventsThenPlanDemoRoute: PagesEventsThenPlanDemoRoute,
}

const PagesEventsLayoutRouteWithChildren =
  PagesEventsLayoutRoute._addFileChildren(PagesEventsLayoutRouteChildren)

interface PagesHireLayoutRouteChildren {
  PagesHireRoute: typeof PagesHireRoute
  PagesHireActivitiesArchitectureRoute: typeof PagesHireActivitiesArchitectureRoute
  PagesHireActivitiesAWSRoute: typeof PagesHireActivitiesAWSRoute
  PagesHireActivitiesAzureRoute: typeof PagesHireActivitiesAzureRoute
  PagesHireBackendRoute: typeof PagesHireBackendRoute
  PagesHireCAERoute: typeof PagesHireCAERoute
  PagesHireActivitiesCareerRoute: typeof PagesHireActivitiesCareerRoute
  PagesHireCompilersRoute: typeof PagesHireCompilersRoute
  PagesHireDatabasesRoute: typeof PagesHireDatabasesRoute
  PagesHireDevopsRoute: typeof PagesHireDevopsRoute
  PagesHireActivitiesDiscoveryRoute: typeof PagesHireActivitiesDiscoveryRoute
  PagesHireDeviceDriversRoute: typeof PagesHireDeviceDriversRoute
  PagesHireDomainEdTechRoute: typeof PagesHireDomainEdTechRoute
  PagesHireEmbeddedRoute: typeof PagesHireEmbeddedRoute
  PagesHireDomainFinTechRoute: typeof PagesHireDomainFinTechRoute
  PagesHireFrontendRoute: typeof PagesHireFrontendRoute
  PagesHireActivitiesGCPRoute: typeof PagesHireActivitiesGCPRoute
  PagesHireHighloadRoute: typeof PagesHireHighloadRoute
  PagesHireActivitiesKubernetesRoute: typeof PagesHireActivitiesKubernetesRoute
  PagesHireLanguagesRoute: typeof PagesHireLanguagesRoute
  PagesHireDomainLogisticsRoute: typeof PagesHireDomainLogisticsRoute
  PagesHireMachineLearningRoute: typeof PagesHireMachineLearningRoute
  PagesHireDomainResearchRoute: typeof PagesHireDomainResearchRoute
  PagesHireActivitiesSalesRoute: typeof PagesHireActivitiesSalesRoute
  PagesHireDomainSecurityRoute: typeof PagesHireDomainSecurityRoute
  PagesHireSimulationRoute: typeof PagesHireSimulationRoute
  PagesHireDomainTelecomRoute: typeof PagesHireDomainTelecomRoute
}

const PagesHireLayoutRouteChildren: PagesHireLayoutRouteChildren = {
  PagesHireRoute: PagesHireRoute,
  PagesHireActivitiesArchitectureRoute: PagesHireActivitiesArchitectureRoute,
  PagesHireActivitiesAWSRoute: PagesHireActivitiesAWSRoute,
  PagesHireActivitiesAzureRoute: PagesHireActivitiesAzureRoute,
  PagesHireBackendRoute: PagesHireBackendRoute,
  PagesHireCAERoute: PagesHireCAERoute,
  PagesHireActivitiesCareerRoute: PagesHireActivitiesCareerRoute,
  PagesHireCompilersRoute: PagesHireCompilersRoute,
  PagesHireDatabasesRoute: PagesHireDatabasesRoute,
  PagesHireDevopsRoute: PagesHireDevopsRoute,
  PagesHireActivitiesDiscoveryRoute: PagesHireActivitiesDiscoveryRoute,
  PagesHireDeviceDriversRoute: PagesHireDeviceDriversRoute,
  PagesHireDomainEdTechRoute: PagesHireDomainEdTechRoute,
  PagesHireEmbeddedRoute: PagesHireEmbeddedRoute,
  PagesHireDomainFinTechRoute: PagesHireDomainFinTechRoute,
  PagesHireFrontendRoute: PagesHireFrontendRoute,
  PagesHireActivitiesGCPRoute: PagesHireActivitiesGCPRoute,
  PagesHireHighloadRoute: PagesHireHighloadRoute,
  PagesHireActivitiesKubernetesRoute: PagesHireActivitiesKubernetesRoute,
  PagesHireLanguagesRoute: PagesHireLanguagesRoute,
  PagesHireDomainLogisticsRoute: PagesHireDomainLogisticsRoute,
  PagesHireMachineLearningRoute: PagesHireMachineLearningRoute,
  PagesHireDomainResearchRoute: PagesHireDomainResearchRoute,
  PagesHireActivitiesSalesRoute: PagesHireActivitiesSalesRoute,
  PagesHireDomainSecurityRoute: PagesHireDomainSecurityRoute,
  PagesHireSimulationRoute: PagesHireSimulationRoute,
  PagesHireDomainTelecomRoute: PagesHireDomainTelecomRoute,
}

const PagesHireLayoutRouteWithChildren = PagesHireLayoutRoute._addFileChildren(
  PagesHireLayoutRouteChildren,
)

interface PagesProjectsLayoutRouteChildren {
  PagesProjectsRoute: typeof PagesProjectsRoute
  PagesProjectsBitsnapRoute: typeof PagesProjectsBitsnapRoute
  PagesProjectsRCNARoute: typeof PagesProjectsRCNARoute
  PagesProjectsThenPlanRoute: typeof PagesProjectsThenPlanRoute
}

const PagesProjectsLayoutRouteChildren: PagesProjectsLayoutRouteChildren = {
  PagesProjectsRoute: PagesProjectsRoute,
  PagesProjectsBitsnapRoute: PagesProjectsBitsnapRoute,
  PagesProjectsRCNARoute: PagesProjectsRCNARoute,
  PagesProjectsThenPlanRoute: PagesProjectsThenPlanRoute,
}

const PagesProjectsLayoutRouteWithChildren =
  PagesProjectsLayoutRoute._addFileChildren(PagesProjectsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PagesHomeRoute: PagesHomeRoute,
  PagesAboutRoute: PagesAboutRoute,
  PagesBlogLayoutRoute: PagesBlogLayoutRouteWithChildren,
  PagesContactsRoute: PagesContactsRoute,
  PagesEventsLayoutRoute: PagesEventsLayoutRouteWithChildren,
  PagesHireLayoutRoute: PagesHireLayoutRouteWithChildren,
  PagesLegalRoute: PagesLegalRoute,
  PagesProjectsLayoutRoute: PagesProjectsLayoutRouteWithChildren,
  PagesShiftRoute: PagesShiftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
